const carListing = [
    {
        carCode: 1,
        carBrand: 'Peugeot',
        carModel: '208',
        carYear: '2015',
        carComment: 'Unico dueño',
        carImage: 'auto-1.jpg',
    },
    {
        carCode: 2,
        carBrand: 'Peugeot',
        carModel: '308',
        carYear: '2020',
        carComment: 'Nafta',
        carImage: 'auto-2.jpg',
    },
    {
        carCode: 3,
        carBrand: 'VW',
        carModel: 'Passat',
        carYear: '2020',
        carComment: 'Nafta',
        carImage: 'auto-3.JPG',
    },
    {
        carCode: 4,
        carBrand: 'VW',
        carModel: 'Gol',
        carYear: '2022',
        carComment: 'Diesel',
        carImage: 'auto-4.JPG',
    },
    {
        carCode: 5,
        carBrand: 'Citroën',
        carModel: 'DS 3 1.6',
        carYear: '2012',
        carComment: 'Automatico',
        carImage: 'auto-5.JPG',
    },
    {
        carCode: 6,
        carBrand: 'Mini Cooper',
        carModel: '',
        carYear: '2015',
        carComment: 'Automatico',
        carImage: 'auto-6.JPG',
    },
    {
        carCode: 7,
        carBrand: 'Peugeot',
        carModel: '308 Cabriolet',
        carYear: '2016',
        carComment: 'Automatico',
        carImage: 'auto-7.JPG',
    },
    {
        carCode: 8,
        carBrand: 'VW',
        carModel: 'Golf',
        carYear: '2017',
        carComment: 'Nafta',
        carImage: 'auto-8.JPG',
    }
]
export default carListing;